### PR TITLE
Add poster image for media atoms.

### PR DESCRIPTION
**Pull request by susiecoleman**
Update thrift definition for poster image for media atoms. Provides more information about the image than just a URL. Subset of the image data from grid.

### CODE REVIEW

**Comment by currysoup** [comment]
The thrift looks good, do we need a version bump somewhere?

**Comment by mchv** [comment]
@susiecoleman why do we prefix with `grid`?
atoms format should be independent of tools

**Comment by mchv** [comment]
why image assets is in `shared` if only used by the media atom?

**Comment by currysoup** [comment]
The media atoms will be using the grid picture selector, so in literal terms it's a grid image.

**Comment by susiecoleman** [comment]
@mchv Yes my logic was basically what @currysoup already said. It's there to be a representation of an image from the grid. I thought it was sensible for it to be shared to try and prevent there being multiple representations of a grid image in the future spread across files.

**Comment by susiecoleman** [comment]
@currysoup bumped version number

**Comment by mchv** [comment]
it should really not be prefixed by `Grid`, it will not be in the content api, so if you do it there we will not be able to use the model easily which break the main point of using `thrift`

**Comment by susiecoleman** [comment]
@mchv Removed grid reference

**Comment by mchv** [comment]
@susiecoleman thanks!

**Comment by clloyd** [comment]
@mchv We store the information that is needed to render and an id to fetch the rest of the information from the grid. It might be extended if we need to add more information for rights collection etc, but rather not duplicate the information grid is storing.

**Comment by mchv** [comment]
@clloyd sounds sensible, thanks for the context!

**Comment by mchv** [comment]
👍

**Pull request merged**
