### PR TITLE
more pluto fields

### PR DESCRIPTION
**Pull request by akash1810**
adds more fields for Pluto, in its own `struct`.

### CODE REVIEW

**Comment by mbarton** [comment]
Why do we need the pluto info in the atom thrift rather than maintaining the mapping separately in the atom maker?

**Comment by akash1810** [comment]
> Why do we need the pluto info in the atom thrift rather than maintaining the mapping separately in the atom maker?

We're saving the thrift model in dynamo.

We can either:
- update thrift model
- change the way we save atoms
- have another dynamo table for this info

The latter two are expensive 😢

**Comment by mbarton** [comment]
I think we're only using the pluto info for our own synchronisation purposes it feels a bit wrong to me having them in thrift and then published through CAPI etc.

I agree we already have quite a few dynamo tables in the atom maker though.

**Comment by akash1810** [comment]
We'd probably want the pluto master id in capi for teleporter

**Comment by akash1810** [comment]
Merging.

@mbarton the fields aren't automatically exposed in a CAPI response.

**Pull request merged**
