### PR TITLE
Add top level title and takenDown change record

### PR DESCRIPTION
**Pull request by marialivia16**
@philmcmahon

### CODE REVIEW

**Comment by philmcmahon** [comment]
Sorry I missed this!

**Comment by mchv** [comment]
I @marialivia16 could we discussed about this as I don't understand the changes

**Comment by mchv** [comment]
As discussed with @marialivia16 @philmcmahon and @clloyd:

-  `title` on the top atom level will be used to display a description of the atom in `tools` and will be populated by all atoms editor. Each atom tool maker is free to keep another `title` field if they need but for new atoms it will be great to avoid to name a field `title` if it has a different purpose.

- `takenDown` change will be populated only the taken down event, it add details about the user who did it and when

**Comment by mchv** [comment]
👍

**Pull request merged**
