### PR TITLE
Publish a Thrift-only artifact

### PR DESCRIPTION
**Pull request by cb372**
Reorganise sbt to publish a jar containing only the Thrift files, as well as the existing artifact that contains both Thrift files and Scrooge-generated classes.

Also bump Scala and sbt.

Note: I published version 0.2.7 while testing this PR, but there are no changes to the models.

### CODE REVIEW

**Comment by rrees** [comment]
I've bumped the JS published version to 1.0.0 as this is clearly now in production. Think it would be sensible to do that for the Maven version as well. SemVar 4TW!

:+1:  to the changes

**Comment by cb372** [comment]
>I've bumped the JS published version to 1.0.0

How did you do that? package.json says `0.2.0-SNAPSHOT.1`

**Comment by rrees** [comment]
No it doesn't! (May have forgotten to push that change :innocent: )

**Comment by cb372** [comment]
OK, I'll merge this and then publish v1.0.0

**Pull request merged**
