### PR TITLE
Add result buckets to the quz content atom

### PR DESCRIPTION
**Pull request by hmgibson23**
Not sure if this is how we want to represent these

\cc @paulmr @chrisfinch

### CODE REVIEW

**Comment by chrisfinch** [comment]
Seems reasonable to me - what about the weighting on answers?

**Comment by hmgibson23** [comment]
Weighting was already there...

**Comment by chrisfinch** [comment]
:+1:

**Comment by chrisfinch** [comment]
@hmgibson23 I'll let you press the delete button ;-)

**Pull request merged**
